services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PORT=3000
    networks:
      - postgres
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - postgres

  postgres:
    image: docker.io/library/postgres:15
    container_name: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

volumes:
  postgres-data:


networks:
  postgres:
